name: accurate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  get:
  google_fonts:
  intl:
  url_launcher:
  google_maps_flutter:
  shared_preferences:
  image_fade:
  map_launcher:
  image_picker:
  firebase_core:
  firebase_messaging:
  google_place:
  flutter_local_notifications:
  path_provider:
  google_places_flutter:
  http_parser:
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.1
  geolocator: ^9.0.0
  permission_handler: ^10.0.0
  cached_network_image:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/


# flutter_icons should be at the root level, not under flutter               # Enable for iOS


flutter_native_splash:
  image: images/icon.png
  color: "#FFFFFF"  # Background color for splash screen

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#FFFFFF"  # Only for Android
  adaptive_icon_foreground: "images/icon.png"  # Only for Android